language: python

sudo: false

env:
    - TOX_ENV=py310-docs
    - TOX_ENV=py310-django4.0.1-drf3.13.1

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV

python:
  - 3.8
  - 3.9
  - 3.10
