language: python

sudo: false

env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=django1.9-drf3.6
    - TOX_ENV=django1.10-drf3.6
    - TOX_ENV=django1.11-drf3.6

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV

python:
  - 3.5
  - 3.6
  - 2.7
