# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Does not change version or update codecov as opposed to main test suite

name: Dev Tests

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ dev, testing ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Lint with flake8
      run: |
        tox -e flake8
    - name: Test repo with tox
      run: tox -v
    - name: Coverage Erase
      run: tox -e clean
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - name: Update rest_friendship/__init__.py file with version tag.
      run: |
        echo "__version__ = '"${{ steps.previoustag.outputs.tag }}"'\n" > ./rest_friendship/__init__.py
    - name: Commit files
      continue-on-error: true
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add VERSION
        git commit -m "Auto-bump version to "${{ steps.previoustag.outputs.tag }}" TEST" -a
    - name: Push changes
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: testing
        force: true
