# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Rest Friendship Test & Bump Version on new Tag

on:
  push:
    tags:
      - '*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Lint with flake8
      run: tox -e flake8
    - name: Test with tox
      run: tox -v
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        python-version: "3.10"
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        python-version: "3.10"
    - name: Update rest_friendship/__init__.py file with tag.
      run: |
        echo "__version__ = '"${{ steps.previoustag.outputs.tag }}"'\n" > ./rest_friendship/__init__.py
      with:
        python-version: "3.10"
    - name: Commit files
      continue-on-error: true
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ./rest_friendship/__init__.py
        git commit -m "Auto-bump version to "${{ steps.previoustag.outputs.tag }}"" -a
      with:
        python-version: "3.10"
    - name: Push changes
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        python-version: "3.10"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
